version: "2"

linters:
  enable:
    - errorlint
    - gocritic
    - misspell
    - revive
    - unconvert
    - usestdlibvars
  exclusions:
    presets:
      - std-error-handling

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/takuo/go-testsplitter
